keyframes_root: data/processed/keyframes
embeddings_root: data/processed/embeddings_clip_vitb16_quickgelu
map_keyframes_root: data/processed/map_keyframes

collection_name: keyframes_clip_vitb16_quickgelu
index:
  field_name: vector
  index_type: HNSW
  metric_type: IP
  params:
    M: 32
    efConstruction: 200
partition_key_field: video_id

model:
  name: ViT-B-16-quickgelu
  pretrained: dfn2b
  device: auto
  precision: fp32
  normalize: true
