keyframes_root: data/processed/keyframes
embeddings_root: data/processed/embeddings_clip_vitb16_quickgelu
map_keyframes_root: data/processed/map_keyframes


index:
  output_dir: data/database/faiss_clip_vitb16_quickgelu
  index_name: keyframes.faiss
  metadata_name: metadata.csv
  metric: cosine

model:
  name: ViT-B-16-quickgelu
  pretrained: metaclip_fullcc
  device: auto
  precision: fp32
  normalize: true